<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>
<%@ page import = "java.sql.*, java.time.LocalDate, java.sql.Date" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
            };  
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
            // Recuperar el último valor de clave generada
            String identityQuery1 = "SELECT id FROM " + schema + ".CREDENTIALS WHERE username = 'sob'";
            ResultSet rs1 = stmt.executeQuery(identityQuery1);
            Long customerid1 = null;
            if (rs1.next()) 
                customerid1 = rs1.getLong(1);
            
            String insertCommentSQL1 = "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'sob@example.com', 'sob', " + customerid1 + ")";
            stmt.executeUpdate(insertCommentSQL1);
            out.println("<pre> -> " + insertCommentSQL1 + "</pre>");
            
            String identityQuery2 = "SELECT id FROM " + schema + ".CUSTOMER WHERE username = 'sob'";
            ResultSet rs2 = stmt.executeQuery(identityQuery2);
            Long customerid2 = null;
            if (rs2.next()) 
                customerid2 = rs2.getLong(1);
            
            String insertCommentSQL2 = "INSERT INTO " + schema + ".ARTICLE VALUES (NEXT VALUE FOR ARTICLE_GEN, 'sob', 'url',0, '" + java.sql.Date.valueOf(LocalDate.now()) + "', '...', 'Introducción a la Programación', 0,  " + customerid2 + ")";
            stmt.executeUpdate(insertCommentSQL2);
            out.println("<pre> -> " + insertCommentSQL2 + "</pre>");
            
            String insertCommentSQL3 = "INSERT INTO " + schema + ".ARTICLE_TOPIC (TOPIC_ID, ARTICLE_ID) VALUES (1,  1)";
            stmt.executeUpdate(insertCommentSQL3);
            out.println("<pre> -> " + insertCommentSQL3 + "</pre>");
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>